### ISSUE TITLE
thredds.server.TdsErrorHandling - uncaught exception

### ISSUE THREAD

**Issue by rkouznetsov** [Unidata/tds#293]
TDS main branch after fixing https://github.com/Unidata/tds/issues/286 logs intermittent uncaught exception on some requests:
```
2022-09-23T09:40:17.310 +0300 [    198691][     151] INFO  - threddsServlet - Remote host: 193.166.192.77 - Request: "GET /thredds/ncss/grid/silam_europe_pollen_v5_8/runs/silam_europe_pollen_v5_8_RUN_2022-09-22T00:00:00Z?var=daymea
n_temp2m,temp_2m_acc,Poll_Rdy2fly_POLLEN_ALDER_m22,heatsum_POLLEN_ALDER_m22,poll_left_POLLEN_ALDER_m22,poll_tot_m2_POLLEN_ALDER_m22,pollen_corr_POLLEN_ALDER_m22,cnc_POLLEN_ALDER_m22,Poll_Rdy2fly_POLLEN_BIRCH_m22,heatsum_POLLEN_BIRC
H_m22,poll_left_POLLEN_BIRCH_m22,poll_tot_m2_POLLEN_BIRCH_m22,pollen_corr_POLLEN_BIRCH_m22,cnc_POLLEN_BIRCH_m22,Poll_Rdy2fly_POLLEN_GRASS_m32,poll_left_POLLEN_GRASS_m32,poll_tot_m2_POLLEN_GRASS_m32,pollen_corr_POLLEN_GRASS_m32,cnc_
POLLEN_GRASS_m32,Poll_Rdy2fly_POLLEN_MUGWORT_m18,poll_left_POLLEN_MUGWORT_m18,cnc_POLLEN_MUGWORT_m18,Poll_Rdy2fly_POLLEN_MUGW1_m18,poll_left_POLLEN_MUGW1_m18,cnc_POLLEN_MUGW1_m18,Poll_Rdy2fly_POLLEN_MUGW2_m18,poll_left_POLLEN_MUGW2
_m18,cnc_POLLEN_MUGW2_m18,Poll_Rdy2fly_POLLEN_MUGW3_m18,poll_left_POLLEN_MUGW3_m18,cnc_POLLEN_MUGW3_m18,Poll_Rdy2fly_POLLEN_MUGW4_m18,poll_left_POLLEN_MUGW4_m18,cnc_POLLEN_MUGW4_m18,Poll_Rdy2fly_POLLEN_MUGW5_m18,poll_left_POLLEN_MU
GW5_m18,cnc_POLLEN_MUGW5_m18,Poll_Rdy2fly_POLLEN_OLIVE_m28,heatsum_POLLEN_OLIVE_m28,poll_left_POLLEN_OLIVE_m28,poll_tot_m2_POLLEN_OLIVE_m28,pollen_corr_POLLEN_OLIVE_m28,cnc_POLLEN_OLIVE_m28,Poll_Rdy2fly_POLLEN_RAGWEED_m18,heatsum_P
OLLEN_RAGWEED_m18,poll_left_POLLEN_RAGWEED_m18,poll_tot_m2_POLLEN_RAGWEED_m18,pollen_corr_POLLEN_RAGWEED_m18,cnc_POLLEN_RAGWEED_m18&spatial=bb&north=56&west=4&east=16&south=46&temporal=range&time_start=2022-09-23T04:00:00Z&time_end
=2022-09-23T04:00:00Z&accept=netcdf3&email=test-download-bavaria HTTP/1.1"
2022-09-23T09:40:17.529 +0300 [    198910][     151] ERROR - thredds.server.TdsErrorHandling - uncaught exception
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.AssertionError
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082) [spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.20.jar:5.3.20]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) [servlet-api.jar:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.20.jar:5.3.20]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.75]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) [spring-security-web-5.6.5.jar:5.6.5]
        at thredds.servlet.filter.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:50) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
        at thredds.servlet.filter.RequestQueryFilter.doFilter(RequestQueryFilter.java:90) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
        at thredds.servlet.filter.HttpHeadFilter.doFilter(HttpHeadFilter.java:47) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) [spring-security-web-5.6.5.jar:5.6.5]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) [spring-security-web-5.6.5.jar:5.6.5]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) [spring-web-5.3.20.jar:5.3.20]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) [spring-web-5.3.20.jar:5.3.20]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.1.jar:2.17.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:196) [catalina.jar:8.5.75]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:8.5.75]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [catalina.jar:8.5.75]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:8.5.75]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698) [catalina.jar:8.5.75]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.75]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:8.5.75]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:366) [catalina.jar:8.5.75]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639) [tomcat-coyote.jar:8.5.75]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:8.5.75]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:847) [tomcat-coyote.jar:8.5.75]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1680) [tomcat-coyote.jar:8.5.75]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.75]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:8.5.75]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:8.5.75]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.75]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.AssertionError
        at ucar.nc2.iosp.hdf5.DataBTree$Node.<init>(DataBTree.java:204) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.iosp.hdf5.DataBTree$DataChunkIterator.<init>(DataBTree.java:128) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.iosp.hdf5.DataBTree.getDataChunkIteratorFilter(DataBTree.java:67) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.iosp.hdf5.H5tiledLayoutBB.<init>(H5tiledLayoutBB.java:94) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:149) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:126) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2122) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable.reallyRead(Variable.java:817) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable._read(Variable.java:768) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable.read(Variable.java:600) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:473) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.dataset.VariableDS._read(VariableDS.java:448) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable.read(Variable.java:600) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft.fmrc.FmrcDataset.read(FmrcDataset.java:1063) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft.fmrc.FmrcDataset.access$200(FmrcDataset.java:74) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft.fmrc.FmrcDataset$ProxyReader1D.reallyRead(FmrcDataset.java:1015) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.dataset.VariableDS._read(VariableDS.java:448) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable.read(Variable.java:600) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable.read(Variable.java:574) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft2.coverage.adapter.DtCoverage.readDataSection(DtCoverage.java:587) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft2.coverage.adapter.DtCoverageAdapter.readData(DtCoverageAdapter.java:388) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft2.coverage.Coverage.readData(Coverage.java:168) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft2.coverage.writer.CFGridCoverageWriter.writeCoverageData(CFGridCoverageWriter.java:437) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft2.coverage.writer.CFGridCoverageWriter.writeFile(CFGridCoverageWriter.java:165) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft2.coverage.writer.CFGridCoverageWriter.write(CFGridCoverageWriter.java:113) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at thredds.server.ncss.controller.NcssGridController.makeCFNetcdfFile(NcssGridController.java:158) ~[classes/:5.5-SNAPSHOT]
        at thredds.server.ncss.controller.NcssGridController.handleRequestGrid(NcssGridController.java:119) ~[classes/:5.5-SNAPSHOT]
        at thredds.server.ncss.controller.NcssGridController.handleRequest(NcssGridController.java:101) ~[classes/:5.5-SNAPSHOT]
        at jdk.internal.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.20.jar:5.3.20]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.20.jar:5.3.20]
        ... 44 more
2022-09-23T09:40:17.560 +0300 [    198941][     151] INFO  - threddsServlet - Request Completed - 500 - -1 - 250
```
The error seems to shoe more often if I run several  requests at the same time (one per time step).  TDS4.6 used to serve such requests smoothly...
Thank you!
More detailed log: [threddsServlet.log.gz](https://github.com/Unidata/tds/files/9631273/threddsServlet.log.gz)

**Comment by rkouznetsov** [comment]
After a day the whole dataset becomes unusable: all requests to this FMRC start making error 500 with very similar backtraces. Restarting tomcat makes some requests passing for some time. Other datasets seem to be not affected by the one that got broken.

**Comment by rkouznetsov** [comment]
Restarting does not reliably prevent TDS from putting the collection into unusable state.  If I make my script to send the requests one-by-one the acquisition  works smoothly (immediately after restart and cleaning caches).

Looks like there is some issue with thread-safety in spring-webmvc-5.3.20 or in cdm-core-5.5.4...

**Comment by haileyajohnson** [comment]
Are these all NCSS requests or are you making other requests as well?

**Comment by rkouznetsov** [comment]
Yes, these are all NCSS.  The only difference is the forecast hour that is requested. Since the data arranged with time as a record dimension and I need them in hourly files, requesting them hour by hour seems reasonable. Sending several requests in parallel speeds up the download. Here is a sample statistics for a batch of 72 hourly requests similar to one in the OP to get one forecast on a freshly-restarted TDS:

| Parallel requests | Files failed at first try | total time for the batch MM:SS|
|--------------| ----------------| -----------------|
|  1       |    0 |  3:37 |
|  2        |   1  | 2:28 |
|  4        |   4  | 1:18 |
|  8        |   10 | 0:49 |

Total time is the time needed to get all the data after needed number of retries, so once the bug has been fixed the timings should become shorter. The numbers may vary a bit, but general tendency is seen: more requests -- faster download.

The statistics is quite reproducible on subsequent polls without TDS restart. After some time, however, the dataset enters a state where all requests fail. This time is about a day, and FMRC is updated daily. These two facts might or might not be connected.

**Comment by tdrwenski** [comment]
We have fixed a similar issue that I believe may also fix these errors. Would you mind trying the latest snapshot to see if this does indeed resolve this issue? You can download the latest snapshot here:

https://downloads.unidata.ucar.edu/tds/5.5/thredds-5.5-SNAPSHOT.war

**Comment by rkouznetsov** [comment]
Thank you! I have updated to the snapshot from your URL (Built-On: 2022-12-16T04:53:53+0000).
Looks like the issue has been gone. 

Now the  above table looks like:

| Parallel requests | Files failed at first try | total time for the batch MM:SS|
|--------------| ----------------| -----------------|
|  4        |   0  | 1:01 |
|  8        |   0 | 0:39 |
|  16       |   0 | 0:34 |

Besides that the SIMULATION_START_DATE  has been corrected. Earlier it was taken from the first file in the collection. Now it seems to be the one from actually download run.

On the server startup (.war deployment) there were some warnings in `threddsServlet.log`
```
2022-12-16T17:08:23.148 +0200 [ 232230187][        ] INFO  - uk.ac.rdg.resc.edal.wms.WmsContextListener - Deregistering JDBC driver org.h2.Driver@5eb108f5
2022-12-16T17:08:30.494 +0200 [ 232237533][        ] INFO  - net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/usr/share/tomcat/apache-tomcat-8.5.75/webapps/thredds/WEB-INF/lib/chronicle-core-2.23.36.jar
2022-12-16T17:08:30.571 +0200 [ 232237610][        ] WARN  - net.openhft.chronicle.map.ChronicleMapBuilder - Recovery operation needs exclusive access to the ChronicleMap or else the result is unspecified including the risk of loosing and/or corrupting
partial or all data.
2022-12-16T17:08:30.571 +0200 [ 232237610][        ] WARN  - net.openhft.chronicle.map.ChronicleMapBuilder - Do not use recovery as a standard way of opening a ChronicleMap.
```
and in `serverStartup.log`  :
```
...
2022-12-16T17:08:29.061+0200 [ 232236100][        ] INFO  org.hibernate.validator.internal.util.Version: HV000001: Hibernate Validator 6.1.5.Final
2022-12-16T17:08:29.673+0200 [ 232236712][        ] WARN  serverStartup: TdsContext.init(): "tds.upload.dir" property isn't defined.
2022-12-16T17:08:29.673+0200 [ 232236712][        ] WARN  serverStartup: TdsContext.init(): "tds.upload.form" property isn't defined.
2022-12-16T17:08:29.673+0200 [ 232236712][        ] WARN  serverStartup: TdsContext.init(): "tds.download.dir" property isn't defined.
2022-12-16T17:08:29.673+0200 [ 232236712][        ] WARN  serverStartup: TdsContext.init(): "tds.download.form" property isn't defined.
2022-12-16T17:08:29.673+0200 [ 232236712][        ] INFO  serverStartup: TdsContext version= 5.5-SNAPSHOT - 2022-12-16T04:53:53+0000
2022-12-16T17:08:29.673+0200 [ 232236712][        ] INFO  serverStartup: TdsContext initialized logging in /content/thredds/logs
...
2022-12-16T17:08:35.822+0200 [ 232242861][        ] INFO  serverStartup: TdsInit: latest maintenance version = 4.6.21
2022-12-16T17:08:35.822+0200 [ 232242861][        ] WARN  serverStartup: Web Start has been deprecated for >Java 9 and is slated for removal - see http://www.oracle.com/technetwork/java/eol-135779.html)
2022-12-16T17:08:35.994+0200 [ 232243033][        ] INFO  serverStartup: TdsInit complete
...
```

I do not know how significant they are.

**Comment by rkouznetsov** [comment]
UPD: catalina.out seem to have quite a few issues still (likely, not related to this bug):
[catalina.out-startup.gz](https://github.com/Unidata/tds/files/10247173/catalina.out-startup.gz)
Any help would be appreciated.

**Comment by tdrwenski** [comment]
> Thank you! I have updated to the snapshot from your URL (Built-On: 2022-12-16T04:53:53+0000). Looks like the issue has been gone.

Great! Glad to hear it! I will close this issue then.

> 
> On the server startup (.war deployment) there were some warnings in `threddsServlet.log`
> 
> ```
> 2022-12-16T17:08:23.148 +0200 [ 232230187][        ] INFO  - uk.ac.rdg.resc.edal.wms.WmsContextListener - Deregistering JDBC driver org.h2.Driver@5eb108f5
> 2022-12-16T17:08:30.494 +0200 [ 232237533][        ] INFO  - net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/usr/share/tomcat/apache-tomcat-8.5.75/webapps/thredds/WEB-INF/lib/chronicle-core-2.23.36.jar
> 2022-12-16T17:08:30.571 +0200 [ 232237610][        ] WARN  - net.openhft.chronicle.map.ChronicleMapBuilder - Recovery operation needs exclusive access to the ChronicleMap or else the result is unspecified including the risk of loosing and/or corrupting
> partial or all data.
> 2022-12-16T17:08:30.571 +0200 [ 232237610][        ] WARN  - net.openhft.chronicle.map.ChronicleMapBuilder - Do not use recovery as a standard way of opening a ChronicleMap.
> ```

I believe these will disappear if you clean the cache directory and restart TDS. It is probably related to us upgrading the ChronicleMap version.

> 
> and in `serverStartup.log` :
> 
> ```
> ...
> 2022-12-16T17:08:29.061+0200 [ 232236100][        ] INFO  org.hibernate.validator.internal.util.Version: HV000001: Hibernate Validator 6.1.5.Final
> 2022-12-16T17:08:29.673+0200 [ 232236712][        ] WARN  serverStartup: TdsContext.init(): "tds.upload.dir" property isn't defined.
> 2022-12-16T17:08:29.673+0200 [ 232236712][        ] WARN  serverStartup: TdsContext.init(): "tds.upload.form" property isn't defined.
> 2022-12-16T17:08:29.673+0200 [ 232236712][        ] WARN  serverStartup: TdsContext.init(): "tds.download.dir" property isn't defined.
> 2022-12-16T17:08:29.673+0200 [ 232236712][        ] WARN  serverStartup: TdsContext.init(): "tds.download.form" property isn't defined.
> 2022-12-16T17:08:29.673+0200 [ 232236712][        ] INFO  serverStartup: TdsContext version= 5.5-SNAPSHOT - 2022-12-16T04:53:53+0000
> 2022-12-16T17:08:29.673+0200 [ 232236712][        ] INFO  serverStartup: TdsContext initialized logging in /content/thredds/logs
> ...
> 2022-12-16T17:08:35.822+0200 [ 232242861][        ] INFO  serverStartup: TdsInit: latest maintenance version = 4.6.21
> 2022-12-16T17:08:35.822+0200 [ 232242861][        ] WARN  serverStartup: Web Start has been deprecated for >Java 9 and is slated for removal - see http://www.oracle.com/technetwork/java/eol-135779.html)
> 2022-12-16T17:08:35.994+0200 [ 232243033][        ] INFO  serverStartup: TdsInit complete
> ...
> ```
> 
> I do not know how significant they are.

These warnings are common and you should be okay-- probably they should be "info" instead of warnings.

> UPD: catalina.out seem to have quite a few issues still (likely, not related to this bug):
[catalina.out-startup.gz](https://github.com/Unidata/tds/files/10247173/catalina.out-startup.gz)
Any help would be appreciated.

These are also just warnings though they look worse because of the stack traces. They shouldn't be a problem. I believe if you clean your webapps directory (remove everything you don't need from $TOMCAT_HOME/webapps), that will remove these warnings.

**Comment by rkouznetsov** [comment]
Great! Thank you! 
webapps has only directories `ROOT` and `thredds`, and a file `thredds.war` that has been deployed. Not much to clean there. Would it be beneficial to stop tomcat and remove the `thredds` directory and let  `thredds.war`  to deploy?

**Comment by tdrwenski** [comment]
> webapps has only directories `ROOT` and `thredds`, and a file `thredds.war` that has been deployed. Not much to clean there. Would it be beneficial to stop tomcat and remove the `thredds` directory and let `thredds.war` to deploy?

You should remove the `webapps/ROOT` in order to get rid of these warnings. Hope that helps!

**Comment by rkouznetsov** [comment]
Thank you! I have removed `ROOT` webapp, and the stack trace has gone indeed.  Beside that there is no more redirection from https://thredds.silam.fmi.fi/ to https://thredds.silam.fmi.fi/thredds/catalog/catalog.html (which was a right thing), and the former URL results in 404...  What would be a right way to set up the redirection?

Also a warning
```
16-Dec-2022 17:47:00.404 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by thredds.server.reify.LoadCommon (file:/usr/share/tomcat/apache-tomcat-8.5.75/webapps/thredds/WEB-INF/classes/) to field java.nio.charset.Charset.defaultCharset
WARNING: Please consider reporting this to the maintainers of thredds.server.reify.LoadCommon
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release                                                                                                                  
16-Dec-2022 17:47:04.633 WARNING [localhost-startStop-1] net.openhft.chronicle.core.internal.cleaner.ReflectionBasedByteBufferCleanerService.<clinit> Make sure you have set the command line option "--illegal-access=permit --add-exports java.base/jdk.internal.ref=ALL-UNNAMED" to enable ReflectionBasedByteBufferCleanerService
initCatalog catalog.xml
```
still appears in catalina.out.

**Comment by tdrwenski** [comment]
> Thank you! I have removed ROOT webapp, and the stack trace has gone indeed. Beside that there is no more redirection from https://thredds.silam.fmi.fi/ to https://thredds.silam.fmi.fi/thredds/catalog/catalog.html (which was a right thing), and the former URL results in 404... What would be a right way to set up the redirection?

You could choose to keep the ROOT webapp and ignore the warnings you were getting.  It looks like there are other ways of achieving the redirect, though I haven't tried this myself, for instance http://tuckey.org/urlrewrite/. If you are using a reverse proxy (what we do on our thredds servers), you can do one of the following:

Apache http:
```
RewriteEngine On
RewriteRule ^/$ /thredds [R,L]
```
Nginx:
```
rewrite ^/$ /thredds last;
```


> 16-Dec-2022 17:47:00.404 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by thredds.server.reify.LoadCommon (file:/usr/share/tomcat/apache-tomcat-8.5.75/webapps/thredds/WEB-INF/classes/) to field java.nio.charset.Charset.defaultCharset
WARNING: Please consider reporting this to the maintainers of thredds.server.reify.LoadCommon
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release                                                                                                                  
16-Dec-2022 17:47:04.633 WARNING [localhost-startStop-1] net.openhft.chronicle.core.internal.cleaner.ReflectionBasedByteBufferCleanerService.<clinit> Make sure you have set the command line option "--illegal-access=permit --add-exports java.base/jdk.internal.ref=ALL-UNNAMED" to enable ReflectionBasedByteBufferCleanerService
initCatalog catalog.xml

You can safely ignore these warnings, and we will look into removing them.

**Comment by rkouznetsov** [comment]
Thank you!  I guess we can live with those warnings for a while.
